let pizzaJson = [
  {
    id: 1,
    name: "Mussarela",
    img: "img/pizza.png",
    price: [35.0, 45.0, 55.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Molho de tomate, camada dupla de mussarela e orégano",
  },
  {
    id: 2,
    name: "Calabresa",
    img: "img/pizza2.png",
    price: [35.0, 45.0, 55.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description:
      "Molho de tomate, mussarela, calabresa fatiada, cebola e orégano",
  },
  {
    id: 3,
    name: "Quatro Queijos",
    img: "img/pizza3.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description:
      "Molho de tomate, camadas de mussarela, provolone, parmessão, gorgonzola e orégano",
  },
  {
    id: 4,
    name: "Brasileira",
    img: "img/pizza4.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description:
      "Molho de tomate, mussarela, calabresa picada, palmito, champignon, azeitonas e orégano",
  },
  {
    id: 5,
    name: "Portuguesa",
    img: "img/pizza5.png",
    price: [35.0, 45.0, 55.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description:
      "Molho de tomate, mussarela, presunto, ovos, cebolas, pimentão, azeitona  e orégano",
  },
  {
    id: 6,
    name: "Moda da Casa",
    img: "img/pizza6.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description:
      "Molho de tomate, mussarela, carne de sol, tomates em cubos, coentro, cebola, azeitona, catupiry e orégano",
  },
  {
    id: 7,
    name: "Banana com canela",
    img: "img/pizza7.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Mussarela, banana, canela e açúcar",
  },
  {
    id: 8,
    name: "Chocolate com morango",
    img: "img/pizza8.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Creme de leite, lascas de chocolate e morangos",
  },
  {
    id: 9,
    name: "Strogonoff",
    img: "img/strogonofftopo.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Creme de Leite, Pedaços de Carne, Champignon, Queijo Mussarela, Batata Palha, Cheiro-Verde.",
  },
  {
    id: 10,
    name: "Chocolate Preto",
    img: "img/chocolatepretotopo.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Creme de leite, chocolate ao leite derretido, leite condensado, granulado de chocolate",
  },
  {
    id: 11,
    name: "Prestígio",
    img: "img/prestigiotopo.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Creme de leite, lascas de chocolate, coco ralado, leite condensado, granulado de chocolate.",
  },
  {
    id: 12,
    name: "Sensação",
    img: "img/sensacaotopo.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Creme de leite, chocolate ao leite derretido, morangos frescos, leite condensado, granulado de chocolate",
  },
  {
    id: 13,
    name: "Confete",
    img: "img/confetetopo.png",
    price: [40.0, 50.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "12 fatias"],
    description: "Creme de leite, chocolate ao leite derretido, confeitos coloridos, leite condensado, granulado de chocolate",
  },
];
